// Code generated by logcopter-gen; DO NOT EDIT.

package compare

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.glazed.pkg.helpers.compare")
