version: "2"

linters:
  default: none
  enable:
    # defaults
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # stuff I'm adding
    - exhaustive
    #    - gochecknoglobals
    #    - gochecknoinits
    - nonamedreturns
    - predeclared
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: 'SA1019: cli.CreateProcessorLegacy'

formatters:
  enable:
    - gofmt
