#!/usr/bin/env bash

prompto get glazed/parameter-types

for i in CommandDescription ParameterDefinition ParameterLayer; do
	oak go definitions --recurse pkg/ --name "$i" --definition-type struct,interface
done
