#!/usr/bin/env bash

echo "// Here are the types that can be used to define parameters in glazed:"
echo
echo "package github.com/go-go-golems/glazed/pkg/cmds/parameters"
echo 
oak go consts pkg/cmds/parameters/parameter-type.go
echo
oak go definitions pkg/cmds/parameters/file.go --name "FileData" --definition-type struct,interface
