#!/usr/bin/env bash

prompto get glazed/parameter-types

echo "package parameters"
echo
oak go definitions pkg/cmds/parameters/parameters.go
echo
oak go definitions pkg/cmds/parameters/parsed-parameter.go
echo
echo
echo "package layers"
echo
oak go definitions pkg/cmds/layers/layer.go
