package web

import (
	"io/fs"
	"net/http"
	"path"
	"strings"
)

// NewSPAHandler returns a handler that serves the frontend assets with SPA
// fallback to index.html for unknown paths. Production builds set PublicFS from
// embedded assets generated by `go generate ./pkg/web`; development/test builds
// use a disk or in-memory fallback from embed_none.go.
func NewSPAHandler() (http.Handler, error) {
	indexBytes, err := fs.ReadFile(PublicFS, "index.html")
	if err != nil {
		return nil, err
	}

	fileServer := http.FileServer(http.FS(PublicFS))
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet && r.Method != http.MethodHead {
			http.NotFound(w, r)
			return
		}

		cleanPath := path.Clean("/" + r.URL.Path)
		if cleanPath == "/" {
			serveIndex(w, r, indexBytes)
			return
		}

		assetPath := strings.TrimPrefix(cleanPath, "/")
		if _, err := fs.Stat(PublicFS, assetPath); err == nil {
			fileServer.ServeHTTP(w, r)
			return
		}

		serveIndex(w, r, indexBytes)
	}), nil
}

func serveIndex(w http.ResponseWriter, r *http.Request, indexBytes []byte) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("Cache-Control", "no-cache, no-store, must-revalidate")
	w.WriteHeader(http.StatusOK)
	if r.Method != http.MethodHead {
		_, _ = w.Write(indexBytes)
	}
}
