// Code generated by logcopter-gen; DO NOT EDIT.

package yaml

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.glazed.pkg.helpers.yaml")
